name: .NET Core

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build the solution
      run:
        dotnet build DotnetGraph/ --configuration Release
    - name: Run unit tests
      run:
        dotnet test DotnetGraph/Test/DotnetGraphTest/DotnetGraphTest.csproj
    - name: Create the Nuget package
      run:
        dotnet pack DotnetGraph/Source/DotnetGraph/ --configuration Release -o out
    - name: Publish the Nuget package
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run:
        dotnet nuget push out/*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json